db_port: 27017
app_dbname: customers
admin_user: admin
admin_password: "{{ lookup('password', 'credentials/' + app_env + '/admin length=15') }}"
app_user: custuser
app_password: "{{ lookup('password', 'credentials/' + app_env + '/' + app_user + ' length=15') }}"
